### ISSUE TITLE
README.md example doesn't appear to work

### ISSUE THREAD

**Issue by KB1RD** [yjs/yjs#195]
I'm not really sure if this is a bug with `yjs` or a bug in the example. I tried running the following example:
```javascript
const Y = require('yjs')

const doc = new Y.Doc()

const ytext = doc.getArray('array')
const undoManager = new Y.UndoManager(ytext)

ytext.insert(0, 'abc')
undoManager.undo()
ytext.toString() // => ''
undoManager.redo()
ytext.toString() // => 'abc'
``` 
The following error was thrown:
```
workdir/node_modules/yjs/dist/yjs.cjs:2944
  content.forEach(c => {
          ^

TypeError: content.forEach is not a function
    at typeListInsertGenericsAfter (workdir/node_modules/yjs/dist/yjs.cjs:2944:11)
    at typeListInsertGenerics (workdir/node_modules/yjs/dist/yjs.cjs:2985:12)
    at workdir/node_modules/yjs/dist/yjs.cjs:3252:9
    at transact (workdir/node_modules/yjs/dist/yjs.cjs:2117:5)
    at YArray.insert (workdir/node_modules/yjs/dist/yjs.cjs:3251:7)
    at Object.<anonymous> (workdir/index.js:8:7)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```
(I replaced the much longer path on my system with `workdir`)

The error appears to happen on the `ytext.insert(0, 'abc')` and seems to have nothing to do with the `Y.UndoManager`. I have the feeling that this is an issue with the example, since the array insert function has the type `insert(index:number, content:Array<object|boolean|Array|string|number|Uint8Array|Y.Type>)`, which wouldn't allow insertion of a string. Changing the insertion to `ytext.insert(0, ['a', 'b', 'c'])` and the `.toString()` calls to `console.log`s fixes the issue and gives the desired output, but provides an array.

**Comment by dmonad** [comment]
Hey @KB1RD ,

thanks for reporting this! It should have been `const ytext = doc.getText('text')` not `const ytext = doc.getArray('array')`.
