### ISSUE TITLE
"Unexpected case" when undoing restored UndoStack

### ISSUE THREAD

**Issue by ISNIT0** [yjs/yjs#203]
# Exception
```
Error: Unexpected case
    at create (/Users/user/Projects/joe-docs/node_modules/lib0/dist/error-55a9a8c8.cjs:14:21)
    at Object.unexpectedCase (/Users/user/Projects/joe-docs/node_modules/lib0/dist/error-55a9a8c8.cjs:31:9)
    at findIndexSS (/Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:1659:15)
    at findIndexCleanStart (/Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:1700:17)
    at getItemCleanStart (/Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:1721:18)
    at /Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:2204:19
    at iterateStructs (/Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:1786:5)
    at /Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:2196:11
    at Map.forEach (<anonymous>)
    at /Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:2184:28
Error: Unexpected case
    at create (/Users/user/Projects/joe-docs/node_modules/lib0/dist/error-55a9a8c8.cjs:14:21)
    at Object.unexpectedCase (/Users/user/Projects/joe-docs/node_modules/lib0/dist/error-55a9a8c8.cjs:31:9)
    at findIndexSS (/Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:1659:15)
    at findIndexCleanStart (/Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:1700:17)
    at getItemCleanStart (/Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:1721:18)
    at /Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:2204:19
    at iterateStructs (/Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:1786:5)
    at /Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:2196:11
    at Map.forEach (<anonymous>)
    at /Users/user/Projects/joe-docs/node_modules/yjs/dist/yjs.cjs:2184:28
```
    
# UndoStack
```json
[
  {
    "ds": {
      "clients": {
        "__map": true,
        "entries": []
      }
    },
    "beforeState": {
      "__map": true,
      "entries": []
    },
    "afterState": {
      "__map": true,
      "entries": [
        [
          685919273,
          13
        ]
      ]
    },
    "meta": {
      "__map": true,
      "entries": []
    }
  },
  {
    "ds": {
      "clients": {
        "__map": true,
        "entries": []
      }
    },
    "beforeState": {
      "__map": true,
      "entries": [
        [
          685919273,
          13
        ]
      ]
    },
    "afterState": {
      "__map": true,
      "entries": [
        [
          685919273,
          26
        ]
      ]
    },
    "meta": {
      "__map": true,
      "entries": []
    }
  },
  {
    "ds": {
      "clients": {
        "__map": true,
        "entries": []
      }
    },
    "beforeState": {
      "__map": true,
      "entries": [
        [
          685919273,
          26
        ]
      ]
    },
    "afterState": {
      "__map": true,
      "entries": [
        [
          685919273,
          40
        ]
      ]
    },
    "meta": {
      "__map": true,
      "entries": []
    }
  },
  {
    "ds": {
      "clients": {
        "__map": true,
        "entries": []
      }
    },
    "beforeState": {
      "__map": true,
      "entries": [
        [
          685919273,
          40
        ]
      ]
    },
    "afterState": {
      "__map": true,
      "entries": [
        [
          685919273,
          53
        ]
      ]
    },
    "meta": {
      "__map": true,
      "entries": []
    }
  },
  {
    "ds": {
      "clients": {
        "__map": true,
        "entries": []
      }
    },
    "beforeState": {
      "__map": true,
      "entries": [
        [
          685919273,
          53
        ]
      ]
    },
    "afterState": {
      "__map": true,
      "entries": [
        [
          685919273,
          66
        ]
      ]
    },
    "meta": {
      "__map": true,
      "entries": []
    }
  },
  {
    "ds": {
      "clients": {
        "__map": true,
        "entries": []
      }
    },
    "beforeState": {
      "__map": true,
      "entries": [
        [
          685919273,
          66
        ]
      ]
    },
    "afterState": {
      "__map": true,
      "entries": [
        [
          685919273,
          80
        ]
      ]
    },
    "meta": {
      "__map": true,
      "entries": []
    }
  },
  {
    "ds": {
      "clients": {
        "__map": true,
        "entries": []
      }
    },
    "beforeState": {
      "__map": true,
      "entries": [
        [
          685919273,
          80
        ]
      ]
    },
    "afterState": {
      "__map": true,
      "entries": [
        [
          685919273,
          92
        ]
      ]
    },
    "meta": {
      "__map": true,
      "entries": []
    }
  },
  {
    "ds": {
      "clients": {
        "__map": true,
        "entries": []
      }
    },
    "beforeState": {
      "__map": true,
      "entries": [
        [
          685919273,
          92
        ]
      ]
    },
    "afterState": {
      "__map": true,
      "entries": [
        [
          685919273,
          102
        ]
      ]
    },
    "meta": {
      "__map": true,
      "entries": []
    }
  }
]
```

# Parse with:
```javascript
function fancyParse(str) {
  return JSON.parse(str, (key, value) => {
    if (value && value.__map) {
      return new Map(value.entries);
    } else if (value && value.__set) {
      return new Set(value.entries);
    } else {
      return value;
    }
  });
}
```

# Doc state:
```json
[
  2,
  2,
  169,
  152,
  137,
  199,
  2,
  0,
  4,
  1,
  5,
  113,
  117,
  105,
  108,
  108,
  48,
  97,
  115,
  100,
  102,
  97,
  115,
  100,
  102,
  10,
  97,
  115,
  100,
  102,
  97,
  115,
  100,
  102,
  10,
  97,
  115,
  100,
  102,
  97,
  115,
  100,
  102,
  10,
  97,
  115,
  100,
  102,
  97,
  115,
  100,
  102,
  97,
  10,
  115,
  100,
  102,
  97,
  115,
  100,
  102,
  97,
  115,
  100,
  102,
  129,
  169,
  152,
  137,
  199,
  2,
  47,
  54,
  1,
  249,
  223,
  134,
  152,
  6,
  0,
  193,
  169,
  152,
  137,
  199,
  2,
  47,
  169,
  152,
  137,
  199,
  2,
  48,
  30,
  2,
  169,
  152,
  137,
  199,
  2,
  1,
  48,
  54,
  249,
  223,
  134,
  152,
  6,
  1,
  0,
  30
]
```

# UndoCode
```javascript
const undoManager = new Y.UndoManager(yText);
undoManager.undoStack = undoStack;
while (undoManager.undoStack.length) {
    undoManager.undo();
}
```

**Comment by dmonad** [comment]
I can't reproduce this issue. It worked for me. I bet you are not doing this:

```js
Y.applyUpdate(ydoc, Uint8Array.from(yourArray))
```

applyUpdate expects an Uint8Array ;)

**Comment by dmonad** [comment]
(If you just apply the array, you wont update the document and hence you get the above error. If you see this error again it basically means that something is missing because Yjs can't find it. Usually, if it exists in the UndoManager, we know that the range of described items exist, so I don't check if all required updates were applied..)
