### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by onemenzel** [yjs/yjs#280]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

The installation fails.

**To Reproduce**

1. `npm i --save yjs`

**Expected behavior**

yjs should install.

**Environment Information**

 - npm@7.5.3
 - node@15.9.0 installed via homebrew
 - yjs@13.5.0 (latest to this date)
 - macOS@11.2.1

**Additional context - NPM error log**

```
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.9.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'i',
0 verbose cli   '--save',
0 verbose cli   'yjs',
0 verbose cli   'y-codemirror',
0 verbose cli   'y-webrtc'
0 verbose cli ]
1 info using npm@7.5.3
2 info using node@v15.9.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/path/to/project/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file: ~/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 verbose npm-session 3ceb86d9658642f3
20 timing npm:load Completed in 25ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 52ms
23 timing idealTree:userRequests Completed in 6ms
24 silly idealTree buildDeps
25 silly fetch manifest yjs@*
26 http fetch GET 304 https://registry.npmjs.org/yjs 4024ms (from cache)
27 silly fetch manifest y-codemirror@*
28 http fetch GET 304 https://registry.npmjs.org/y-codemirror 684ms (from cache)
29 silly fetch manifest codemirror@^5.52.2
30 http fetch GET 304 https://registry.npmjs.org/codemirror 73ms (from cache)
31 silly fetch manifest y-webrtc@*
32 http fetch GET 304 https://registry.npmjs.org/y-webrtc 837ms (from cache)
33 silly placeDep ROOT y-codemirror@2.1.0 OK for: obsidian-sample-plugin@0.9.7 want: *
34 silly placeDep ROOT yjs@13.5.0 OK for: y-codemirror@2.1.0 want: ^13.0.0
35 silly placeDep ROOT codemirror@5.59.2 OK for: y-codemirror@2.1.0 want: ^5.52.2
36 silly placeDep ROOT y-webrtc@10.1.8 OK for: obsidian-sample-plugin@0.9.7 want: *
37 silly placeDep ROOT yjs@13.5.0 KEEP for: obsidian-sample-plugin@0.9.7 want: *
38 silly fetch manifest lib0@^0.2.35
39 silly fetch manifest ws@^7.2.0
40 silly fetch manifest lib0@^0.2.34
41 silly fetch manifest simple-peer@^9.9.3
42 silly fetch manifest y-protocols@^1.0.1
43 http fetch GET 304 https://registry.npmjs.org/simple-peer 63ms (from cache)
44 http fetch GET 304 https://registry.npmjs.org/ws 193ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/lib0 772ms (from cache)
46 http fetch GET 304 https://registry.npmjs.org/y-protocols 781ms (from cache)
47 timing idealTree:#root Completed in 6427ms
48 timing idealTree:node_modules/codemirror Completed in 0ms
49 silly placeDep ROOT lib0@0.2.36 OK for: y-codemirror@2.1.0 want: ^0.2.35
50 silly fetch manifest isomorphic.js@^0.2.0
51 http fetch GET 304 https://registry.npmjs.org/isomorphic.js 913ms (from cache)
52 timing idealTree:node_modules/y-codemirror Completed in 916ms
53 silly placeDep ROOT isomorphic.js@0.2.0 OK for: lib0@0.2.36 want: ^0.2.0
54 timing idealTree:node_modules/lib0 Completed in 1ms
55 timing idealTree:node_modules/isomorphic.js Completed in 0ms
56 silly fetch manifest bufferutil@^4.0.1
57 http fetch GET 304 https://registry.npmjs.org/bufferutil 64ms (from cache)
58 silly fetch manifest utf-8-validate@^5.0.2
59 http fetch GET 304 https://registry.npmjs.org/utf-8-validate 62ms (from cache)
60 silly placeDep ROOT simple-peer@9.9.3 OK for: y-webrtc@10.1.8 want: ^9.9.3
61 silly placeDep ROOT ws@7.4.3 OK for: y-webrtc@10.1.8 want: ^7.2.0
62 silly placeDep ROOT y-protocols@1.0.4 OK for: y-webrtc@10.1.8 want: ^1.0.1
63 silly fetch manifest buffer@^6.0.2
64 silly fetch manifest debug@^4.2.0
65 silly fetch manifest err-code@^2.0.3
66 silly fetch manifest get-browser-rtc@^1.0.2
67 silly fetch manifest queue-microtask@^1.2.0
68 silly fetch manifest randombytes@^2.1.0
69 silly fetch manifest readable-stream@^3.6.0
70 http fetch GET 304 https://registry.npmjs.org/randombytes 294ms (from cache)
71 http fetch GET 304 https://registry.npmjs.org/err-code 302ms (from cache)
72 http fetch GET 304 https://registry.npmjs.org/buffer 317ms (from cache)
73 http fetch GET 304 https://registry.npmjs.org/queue-microtask 308ms (from cache)
74 http fetch GET 304 https://registry.npmjs.org/get-browser-rtc 339ms (from cache)
75 http fetch GET 304 https://registry.npmjs.org/debug 348ms (from cache)
76 http fetch GET 304 https://registry.npmjs.org/readable-stream 338ms (from cache)
77 timing idealTree:node_modules/y-webrtc Completed in 486ms
78 silly placeDep ROOT buffer@6.0.3 OK for: simple-peer@9.9.3 want: ^6.0.2
79 silly placeDep ROOT debug@4.3.1 OK for: simple-peer@9.9.3 want: ^4.2.0
80 silly placeDep ROOT err-code@2.0.3 OK for: simple-peer@9.9.3 want: ^2.0.3
81 silly placeDep ROOT get-browser-rtc@1.1.0 OK for: simple-peer@9.9.3 want: ^1.0.2
82 silly placeDep ROOT queue-microtask@1.2.2 OK for: simple-peer@9.9.3 want: ^1.2.0
83 silly placeDep ROOT randombytes@2.1.0 OK for: simple-peer@9.9.3 want: ^2.1.0
84 silly placeDep ROOT readable-stream@3.6.0 OK for: simple-peer@9.9.3 want: ^3.6.0
85 silly fetch manifest base64-js@^1.3.1
86 silly fetch manifest ieee754@^1.2.1
87 silly fetch manifest ms@2.1.2
88 silly fetch manifest safe-buffer@^5.1.0
89 silly fetch manifest string_decoder@^1.1.1
90 silly fetch manifest util-deprecate@^1.0.1
91 http fetch GET 304 https://registry.npmjs.org/base64-js 85ms (from cache)
92 http fetch GET 304 https://registry.npmjs.org/string_decoder 92ms (from cache)
93 http fetch GET 304 https://registry.npmjs.org/safe-buffer 97ms (from cache)
94 http fetch GET 304 https://registry.npmjs.org/util-deprecate 94ms (from cache)
95 http fetch GET 304 https://registry.npmjs.org/ieee754 102ms (from cache)
96 http fetch GET 304 https://registry.npmjs.org/ms 102ms (from cache)
97 timing idealTree:node_modules/simple-peer Completed in 115ms
98 silly placeDep ROOT base64-js@1.5.1 OK for: buffer@6.0.3 want: ^1.3.1
99 silly placeDep ROOT ieee754@1.2.1 OK for: buffer@6.0.3 want: ^1.2.1
100 timing idealTree:node_modules/buffer Completed in 4ms
101 timing idealTree:node_modules/base64-js Completed in 0ms
102 silly placeDep ROOT ms@2.1.2 OK for: debug@4.3.1 want: 2.1.2
103 timing idealTree:node_modules/debug Completed in 1ms
104 timing idealTree:node_modules/err-code Completed in 0ms
105 timing idealTree:node_modules/get-browser-rtc Completed in 0ms
106 timing idealTree:node_modules/ieee754 Completed in 0ms
107 timing idealTree:node_modules/ms Completed in 0ms
108 timing idealTree:node_modules/queue-microtask Completed in 0ms
109 silly placeDep ROOT safe-buffer@5.2.1 OK for: randombytes@2.1.0 want: ^5.1.0
110 timing idealTree:node_modules/randombytes Completed in 1ms
111 silly placeDep ROOT string_decoder@1.3.0 OK for: readable-stream@3.6.0 want: ^1.1.1
112 silly placeDep ROOT util-deprecate@1.0.2 OK for: readable-stream@3.6.0 want: ^1.0.1
113 timing idealTree:node_modules/readable-stream Completed in 3ms
114 timing idealTree:node_modules/safe-buffer Completed in 0ms
115 timing idealTree:node_modules/string_decoder Completed in 0ms
116 timing idealTree:node_modules/util-deprecate Completed in 0ms
117 timing idealTree:node_modules/ws Completed in 0ms
118 timing idealTree:node_modules/y-protocols Completed in 0ms
119 timing idealTree:node_modules/yjs Completed in 0ms
120 timing idealTree:buildDeps Completed in 7957ms
121 timing idealTree:fixDepFlags Completed in 1ms
122 timing idealTree Completed in 8020ms
123 timing reify:loadTrees Completed in 8021ms
124 timing reify:diffTrees Completed in 3ms
125 silly reify moves {}
126 timing reify:retireShallow Completed in 0ms
127 timing reify:createSparse Completed in 9ms
128 timing reify:loadBundles Completed in 0ms
129 timing reifyNode:node_modules/get-browser-rtc Completed in 282ms
130 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 290ms
131 timing auditReport:getReport Completed in 291ms
132 timing auditReport:init Completed in 0ms
133 timing reify:audit Completed in 291ms
134 timing reifyNode:node_modules/ms Completed in 292ms
135 timing reifyNode:node_modules/ieee754 Completed in 294ms
136 timing reifyNode:node_modules/queue-microtask Completed in 294ms
137 timing reifyNode:node_modules/util-deprecate Completed in 297ms
138 timing reifyNode:node_modules/string_decoder Completed in 298ms
139 timing reifyNode:node_modules/base64-js Completed in 297ms
140 timing reifyNode:node_modules/isomorphic.js Completed in 299ms
141 timing reifyNode:node_modules/safe-buffer Completed in 306ms
142 timing reifyNode:node_modules/randombytes Completed in 306ms
143 timing reifyNode:node_modules/debug Completed in 310ms
144 timing reifyNode:node_modules/err-code Completed in 314ms
145 timing reifyNode:node_modules/buffer Completed in 327ms
146 timing reifyNode:node_modules/simple-peer Completed in 357ms
147 timing reifyNode:node_modules/ws Completed in 465ms
148 timing reifyNode:node_modules/readable-stream Completed in 715ms
149 timing reifyNode:node_modules/y-protocols Completed in 818ms
150 timing reifyNode:node_modules/y-webrtc Completed in 937ms
151 timing reifyNode:node_modules/yjs Completed in 1039ms
152 timing reifyNode:node_modules/y-codemirror Completed in 1166ms
153 timing reifyNode:node_modules/lib0 Completed in 1374ms
154 timing reifyNode:node_modules/codemirror Completed in 1454ms
155 timing reify:unpack Completed in 1456ms
156 timing reify:unretire Completed in 0ms
157 timing build:queue Completed in 5ms
158 timing build:link:node_modules/y-webrtc Completed in 2ms
159 timing build:link Completed in 3ms
160 info run yjs@13.5.0 postinstall node_modules/yjs node ./sponsor-y.js
161 info run yjs@13.5.0 postinstall { code: 1, signal: null }
162 timing reify:rollback:createSparse Completed in 292ms
163 timing reify:rollback:retireShallow Completed in 0ms
164 timing command:install Completed in 9931ms
165 verbose stack Error: command failed
165 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
165 verbose stack     at ChildProcess.emit (node:events:378:20)
165 verbose stack     at maybeClose (node:internal/child_process:1067:16)
165 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
166 verbose pkgid yjs@13.5.0
167 verbose cwd /path/to/project
168 verbose Darwin 20.3.0
169 verbose argv "/usr/local/Cellar/node/15.9.0/bin/node" "/usr/local/bin/npm" "i" "--save" "yjs" "y-codemirror" "y-webrtc"
170 verbose node v15.9.0
171 verbose npm  v7.5.3
172 error code 1
173 error path /path/to/project/node_modules/yjs
174 error command failed
175 error command sh -c node ./sponsor-y.js
176 error node:internal/modules/cjs/loader:478
176 error       throw e;
176 error       ^
176 error
176 error Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/logging.cjs' is not defined by "exports" in /path/to/project/node_modules/lib0/package.json
176 error     at new NodeError (node:internal/errors:329:5)
176 error     at throwExportsNotFound (node:internal/modules/esm/resolve:337:9)
176 error     at packageExportsResolve (node:internal/modules/esm/resolve:562:3)
176 error     at resolveExports (node:internal/modules/cjs/loader:472:36)
176 error     at Function.Module._findPath (node:internal/modules/cjs/loader:512:31)
176 error     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:909:27)
176 error     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
176 error     at Module.require (node:internal/modules/cjs/loader:995:19)
176 error     at require (node:internal/modules/cjs/helpers:92:18)
176 error     at Object.<anonymous> (/path/to/project/node_modules/yjs/sponsor-y.js:2:13) {
176 error   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
176 error }
177 verbose exit 1
```

**Comment by jayaddison** [comment]
This could be related to `npm` version - from local testing, it's also reproducible with `npm` v7.5.2, and does **not** appear with `npm` v6.14.4.

**Comment by dmonad** [comment]
Hi @jayaddison ,

Thanks for the report. I upgraded `lib0` to use [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports). It seems npm v7 introduced some changes to the feature that I didn't expect. I fixed it in the latest release. `npm update` should fix the issue.

**Comment by jayaddison** [comment]
@dmonad No problem; yep, after updating dependencies, the `ERR_PACKAGE_PATH_NOT_EXPORTED` error no longer occurs.

**Comment by jayaddison** [comment]
(credit also due to @onemenzel for discovering and reporting the issue)

**Comment by dmonad** [comment]
Whoops, of course. Thanks @onemenzel for reporting. In the hurry I didn't notice there were two participants.

**Comment by onemenzel** [comment]
you're welcome ^^
