### ISSUE TITLE
Y.applyUpdate in BindState fails when image is embedded

### ISSUE THREAD

**Issue by mattch** [yjs/yjs#345]
Everything works great except when an image is embedded in a document.  When an image is embedded via standard Quill toolbar, it looks great in the editor and it even syncs up well with other editors.  The issue happens when the document is saved as Y.encodeStateAsUpdate(doc) and an Y.applyUpdate(yDoc, doc) is done to restore the document. Without an image, the document restores perfectly. But with an image (very small 5k), I get the following error message.  It seems that lib0 is not happy with the stored data of Y.encodeStateAsUpdate when it contains an image.   Any help is much appreciated. Thanks!

```
TypeError: decoder.arr.subarray is not a function
    at Object.readVarString (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/lib0/decoding.js:341:35)
    at UpdateDecoderV1.readJSON (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/utils/UpdateDecoder.js:114:32)
    at Array.readContentEmbed (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/structs/ContentEmbed.js:98:69)
    at readItemContent (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/structs/Item.js:695:83)
    at readClientsStructRefs (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/utils/encoding.js:164:13)
    at /Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/utils/encoding.js:391:16
    at transact (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/utils/Transaction.js:399:5)
    at readUpdateV2 (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/utils/encoding.js:384:3)
    at applyUpdateV2 (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/utils/encoding.js:479:3)
    at Object.applyUpdate (/Volumes/FastSSD/workspace/comeetingroom/src/yjsserver/node_modules/yjs/src/utils/encoding.js:493:6

```

Here's the relevant parts of my code:
   
         setPersistence({
            bindState: async (room: string, yDoc: WSSharedDoc) => {
                ServerDao.getDoc(room)
                    .then(result => {
                        if (Boolean(result.ydoc)) {
                            Y.applyUpdate(yDoc, result.ydoc);
                        }
                    })
                    .catch(reason => {
                        console.log("BindState failed", room, reason)
                    });

                yDoc.on('update', (update: Uint8Array, origin: any, doc: WSSharedDoc) => {
                    ServerDao.updateDoc(room, Y.encodeStateAsUpdate(doc))
                        .then(response => {
                        })
                        .catch(reason => {
                            console.log("BindState failed", room, reason)
                        });
                });
        })

Environment details:
    "mongodb": "^3.6.10",
    "express": "^4.17.1",
    "lodash": "^4.17.21",
    "node-fetch": "^2.6.6",
    "ws": "^8.0.0",
    "y-protocols": "^1.0.5",
    "yjs": "^13.5.12"
    "quill": "^1.3.7",
    "react": "^17.0.2",
    "react-quill": "^1.3.5",
    "y-quill": "^0.1.4",
    "y-websocket": "^1.3.16",
    "yjs": "^13.5.12"

**Comment by dmonad** [comment]
I can't reproduce this issue. I tried to reproduce this issue by encoding the document and applying it to a different document. Everything works fine even for larger images (I tested <50kb).

The issue is more likely that the update is not a real Uint8Array (a node buffer works as well). Hence the method `decoder.arr.subarray` does not exist. 

From the structure of your application, it looks like you are using JSON encoding for encoding Yjs updates. The provided document update is probably a normal Array. This is a performance nightmare and a waste of bandwidth. Please read this section: https://docs.yjs.dev/api/document-updates#example-base64-encoding

**Comment by mattch** [comment]
Thanks!!  That worked. 

Just curious, why did it work for documents without images?  If the data was being corrupted by being transmitted in the wrong format, I would suspect that it would not work for any document, not just ones with images embedded.

**Comment by dmonad** [comment]
Because we only need the subarray method for copying large contents efficiently.
