### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by tyrauber** [yjs/yjs#381]
**Describe the bug**

I am interested in exploring the use yjs in react-native and expo, using [valitio-yjs](https://github.com/dai-shi/valtio-yjs) and [y-websocket](https://github.com/yjs/y-websocket).  I've started by porting the [valtio-yjs-demo](https://codesandbox.io/s/ox3iy?file=/src/App.js:61-72) to react-native. Here is a [an expo snack](https://snack.expo.dev/@tyrauber/valtio-yjs-expo) for the purpose of developing and testing the implementation. 

Unfortunately, there are some issues with importing yjs in react-native, specifically related to the dependency lib0. I believe this may be an issue upstream issue in lib0, but I thought I'd report it here first as yjs is loading lib0.

The [snack](https://snack.expo.dev/@tyrauber/valtio-yjs-expo) fails to resolve yjs as a dependency due to lib0:

```
Failed to resolve dependency 'yjs@^13.5.24' (export 'Observable' (imported as 'Observable') was not found in 'lib0/observable' (module has no exports)
```

If you download the example and run it locally, the metro.config.js file, when configured to resolve .mjs and .cjs files, successfully imports and runs in the web browser. But runs into some errors when trying to run it in the iOS simulator:

```
While trying to resolve module `isomorphic.js` from file `~/valtio-yjs-expo/node_modules/lib0/dist/random.cjs`, the package `~/valtio-yjs-expo/node_modules/isomorphic.js/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`~/valtio-yjs-expo/node_modules/isomorphic.js/browser.mjs`. Indeed, none of these files exist:
```

This issue is also referenced at  [dai-shi/valtio-yjs/issues/20](https://github.com/dai-shi/valtio-yjs/issues/20).

Steps to reproduce the issue:

1. Download the [zip](https://snack.expo.dev/@tyrauber/valtio-yjs-expo)
2. install the dependencies `yarn`
3. run in the browser `yarn web` - success
4. run in the iOS simulator `yarn ios` - fail

**Expected behavior**

**Environment Information**

    "yjs": "^13.5.24",
    "lib0": "^0.2.43",
    "valtio": "^1.2.9",
    "valtio-yjs": "^0.3.0",
    "y-websocket": "^1.3.18"

**Comment by ctomacheski** [comment]
I ran into this same issue for `isomorphic` module and a similar issue for `yjs` module. The fix I found is adding the respective file extensions from the `main` file of each module to `sourceExts` in the `metro.config.js` file. Something like this:

```
const defaultSourceExts =
  require('metro-config/src/defaults/defaults').sourceExts;

module.exports = {
 ...
  resolver: {
    sourceExts: [...defaultSourceExts, 'cjs', 'mjs'],
    ...
  }
};
```

**Comment by gerwim** [comment]
Whilst for me the `isomorphic.js` issue is fixed by adding the `mjs` in the sourceExts resolver (as seen here: https://github.com/dmonad/lib0/issues/35#issuecomment-1039788491)

It actually crashes (`y-websocket`):
```
TypeError: window.addEventListener is not a function. (In 'window.addEventListener('beforeunload', _this._beforeUnloadHandler)', 'window.addEventListener' is undefined)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://10.10.10.130:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:366021:3 in global code
```

**Comment by andrioid** [comment]
> For now, I've implemented my own sync strategy which works perfectly fine! :)

@gerwim For those of us who are considering the same route, can you share a bit of how you solved your issue?

**Comment by gerwim** [comment]
> > For now, I've implemented my own sync strategy which works perfectly fine! :)
> 
> 
> 
> @gerwim For those of us who are considering the same route, can you share a bit of how you solved your issue?
> 
> 

My solution is fairly simple. I basically save the document as an update by using `Y.encodeStateAsUpdateV2(sharedDocument)` into a database table. My application works with so called rooms. Each client connecting to the same room are signaled when there is an update to this table (each client is responsible for its own row) and new updates are applied immediately.

**Comment by andrioid** [comment]
I can't even import YJS in the latest Expo. Fails on "crypto" being an unknown property. Anything you had to in particular to use the core YJS library? I'm not attempting anything fancy, yet 😄

**Comment by gerwim** [comment]
> I can't even import YJS in the latest Expo. Fails on "crypto" being an unknown property. Anything you had to in particular to use the core YJS library? I'm not attempting anything fancy, yet 😄 

No, I don't think so. Do you have crypto installed? I have a custom dev client though. I do not use the Expo app.

**Comment by andrioid** [comment]
I have "expo-crypto" installed, but AFAIK it doesn't do any shimming. Sorry to hijack your thread, but it has a descriptive name for problem.

What crypto library are you using?

**Comment by andrioid** [comment]
Got it to run, without ejecting from Expo (in case anyone else finds this). Install [react-native-random-values](https://github.com/LinusU/react-native-get-random-values)

index.ts (your entrypoint file)
```
import "react-native-get-random-values";
```

Then restart the dev server and reload the app.

**Comment by CallumHemsley** [comment]
> Update: I have yjs and y-websocket working with Expo 48 and Expo Go (React Native 0.71). I have a little demo app running on Android simulator, my iOS device and communicating with the y-websocket server. Each device sends a string like saying their platform is better e.g. "android is better", "ios is better" on an interval, competing for the document. Working great so far.
> 
> In case other people are interested, I'll outline how I got it working. It's not without "hacks", but it works.
> 
> ### Installing and adding polyfills
> yjs and y-websocket depend on creating random values (of various types) from the crypto API. Other polyfills might work, but this one worked best for me.
> 
> ```
> expo install expo-standard-web-crypto
> ```
> 
> In your entry-point (before trying to do anything)
> 
> ```
> global.Buffer = global.Buffer || require("buffer").Buffer;
> import { polyfillWebCrypto } from "expo-standard-web-crypto";
> polyfillWebCrypto();
> ```
> 
> ### Patching the weboscket-provider
> This part could obviously be done in a more elegant way, but I'm still in the prototype stage.
> 
> Copy the contents of `src/y-websocket.js` from [y-websocket](https://github.com/yjs/y-websocket/) into your project somewhere.
> 
> The reason for getting `undefined is not a function` errors when initializing the Websocket provider was the following. It checks if we're a browser and if we're not, it assumes we're Node.js (we're not).
> 
> ```
>     // if (typeof window !== "undefined") {
>     //   window.addEventListener("unload", this._unloadHandler);
>     // } else if (typeof process !== "undefined") {
>     //   process.on("exit", this._unloadHandler);
>     // }
> ```
> 
> I'm using a Context Provider in React to handle my document, so I'll do my cleanup there instead. But, obviously this needs a cleaner fix at some point.
> 
> ![Screenshot 2023-05-07 085433](https://user-images.githubusercontent.com/271599/236662626-714714de-b68f-4ad0-a261-9c952bd6859d.png)
> 
> I hope this helps anyone wanting to try out yjs and React Native.

Hey @andrioid do you have an example repo I could see? Thanks.

**Comment by andrioid** [comment]
No sorry. I gave up and getting yjs to work for now

**Comment by jacobcoro** [comment]
> No sorry. I gave up and getting yjs to work for now

Oh no! So what was the end result? It seems like from your post above it was working? What issues did you encounter. I was just about to try this.

**Comment by andrioid** [comment]
I ran into problems with the Expo dev server where YJS constantly complains about being imported twice. According to the threads it can cause greater problems, so the warning isn’t safe to ignore.

I’m exploring JSON joy’s CRDT at the moment

**Comment by jacobcoro** [comment]
> I ran into problems with the Expo dev server where YJS constantly complains about being imported twice. According to the threads it can cause greater problems, so the warning isn’t safe to ignore.
> 
> I’m exploring JSON joy’s CRDT at the moment

Hmm. I ran into that before and I think I solved it by just making sure y-websockets was using the same yjs version. You can search through the package-lock to see if there is more than one version? Was it making weird behavior or anything? I'm gonna go ahead and try this then. I will let you know what I find

**Comment by dmonad** [comment]
I can polyfill the `crypto` module directly in lib0 for react-native. That shouldn't be a big problem.

Regarding the `undefined` issue in y-websocket, you probably need to polyfill WebSocket:

https://github.com/yjs/y-websocket/?tab=readme-ov-file#client-code-in-nodejs 

Remirror has been using Yjs for a while, so I assumed it would work out of the box.

**Comment by andrioid** [comment]
> I can polyfill the crypto module directly in lib0 for react-native. That shouldn't be a big problem.
That would certainly make adoption easier, but not a deal-breaker.

> Remirror has been using Yjs for a while, so I assumed it would work out of the box

Seems they abandoned it. The package repo link is a 404 and this:
https://github.com/remirror/remirror/discussions/779

Regarding the double import warning/error; it wasn't acting strange and I suspect it has something to do with how the Metro bundler handles Android/iOS vs web. At least it mostly shows up when I'm trying to develop for both (which, is want). I think Yjs has some real potential for offline-first apps w. React Native - but it just didn't feel solid with my console filling up with warnings.

I have Easter vacation now, so maybe I'll give it another go and keep you folks informed.

**Comment by dmonad** [comment]
Ah okay. That probably has something to do with reacts "fast-refresh" feature. 

Just put `// @refresh reset` anywhere in all files that import yjs. Or disable it completely.

https://reactnative.dev/docs/fast-refresh

This will avoid react importing Yjs over and ever again.

**Comment by raghavsethi** [comment]
@dmonad Thanks so much for your work on Y.js and family. We just switched to it and it's working like a charm - except the react-native bit (also using Expo). If you'd be willing to polyfill crypto in lib0 that would be amazing!

**Comment by dmonad** [comment]
Awesome, happy to hear that!

If your company becomes a monthly sponsor (you determine the value), I'd be inclined to do that 😇

**Comment by jacobcoro** [comment]
I think the bigger challenge is polyfilling local persistence. Following the advice above I got it working in in-app memory, but I still have not been able to get a y-indexedDB polyfill working. I tried this one as well: https://github.com/malte-j/y-op-sqlite#readme but it seems half-formed at the moment (not even a proper dist folder/entry file). I have not tried [y-level-db](https://github.com/yjs/y-leveldb) yet but I see there is a [react-native level-db](https://github.com/greentriangle/react-native-leveldb) so that could work, but it seems you need to `ios pod install` so you can't use expo.

**Comment by brentvatne** [comment]
> I have not tried [y-level-db](https://github.com/yjs/y-leveldb) yet but I see there is a [react-native level-db](https://github.com/greentriangle/react-native-leveldb) so that could work, but it seems you need to `cd ios && pod install` so you can't use expo.

heads up that this is not a limitation of expo, just the sandbox app 'expo go' - https://docs.expo.dev/workflow/overview/

**Comment by andrioid** [comment]
I've used Expo file API to store them directly on the device. That worked reasonably well.

**Comment by hesselbom** [comment]
> I've used Expo file API to store them directly on the device. That worked reasonably well.

Would you like to share your solution? Could also be cool with a y-expo-file provider or something, think it could be appreciated by many!

**Comment by brentvatne** [comment]
@hesselbom - i forked y-op-sqlite and adapted it to expo-sqlite, works pretty well from my tests. https://github.com/brentvatne/y-expo-sqlite. note: this uses the new expo-sqlite api from sdk 51

**Comment by jacobcoro** [comment]
@brentvatne Maybe make a PR on the original? I raised on issue about how it was not working https://github.com/malte-j/y-op-sqlite/issues/1

**Comment by jacobcoro** [comment]
I don't think the yjs website should link to it yet until it is ready to actually use

**Comment by hesselbom** [comment]
FYI, I use y-op-sqlite in my React Native project now by applying the following patch (using patch-package) which exposes the src/index.ts file when importing. My project is in TypeScript so might only work if using TypeScript. 

```patch
diff --git a/node_modules/y-op-sqlite/package.json b/node_modules/y-op-sqlite/package.json
index 412152d..38c9076 100644
--- a/node_modules/y-op-sqlite/package.json
+++ b/node_modules/y-op-sqlite/package.json
@@ -2,9 +2,7 @@
   "name": "y-op-sqlite",
   "version": "1.0.4",
   "description": "",
-  "main": "./y-op-sqlite.cjs",
-  "module": "./y-op-sqlite.mjs",
-  "types": "./index.d.ts",
+  "main": "./src/index.ts",
   "sideEffects": false,
   "type": "module",
   "keywords": [
```

**Comment by malte-j** [comment]
Hi, library author of y-op-sqlite here, I've just updated the package and the build process and got it working for me again, should be working without the patching now. Thanks for the interest!
