### ISSUE TITLE
n.forEach is not a function in typeListInsertGenericsAfter

### ISSUE THREAD

**Issue by achs0** [yjs/yjs#429]
**Checklist**

* [/] Are you reporting a bug? 
* [/] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
I get an "n is not a function error" when trying to use an y.Array. The stacktrace looks like this:

`test array F {_item: null, _map: Map(0), _start: null, doc: Q, _length: 0, …}doc: Q {_observers: Map(3), gc: true, clientID: 1755740483, guid: '95eff6d1-1ddf-4c19-87f7-93becf5cbbaa', gcFilter: ƒ, …}_dEH: Nt {l: Array(0)}_eH: Nt {l: Array(0)}_item: null_length: 0_map: Map(0) {size: 0}_prelimContent: null_searchMarker: []_start: nulllength: (...)parent: (...)_first: (...)[[Prototype]]: I
yjs.js:2 Uncaught TypeError: n.forEach is not a function
    at typeListInsertGenericsAfter (yjs.js:2:43314)
    at typeListInsertGenerics (yjs.js:2:44060)
    at yjs.js:2:46744
    at transact (yjs.js:2:28048)
    at F.insert (yjs.js:2:46729)
    at test_yjs.html:20:10`

**To Reproduce**
I built a jsfiddle: with some basic code for reproduction, just take a look at the console. then you will find the exception.
https://jsfiddle.net/0xj4y1k6/ 

**Expected behavior**
i tried to use the array like described in the documentation.

**Environment Information**
 - Newest Yjs version from esm.sh
 - yjs and y-websocket with demo-server

**Additional context**
Hope this is just a minor bug (or i used the framework wrong)
A ymap worked fine in the example, but only when using a string. If i try to use an array in the map it also crashes. 

PS. This is a great library! Thanks for the great work :-)

**Comment by achs0** [comment]
I think i found the root cause, after checking the source code of yjs. 

The push and insert methods of Y.Array only accept arrays instead of simple types. 

I was a little bit confused since the API looks like it was designed after a "standard" javascript Array. So i tried to add only one item to the array. 

Workaround for this is to add one item as an array. But i don't know if this is the right way to go :-) @dmonad am i right?

After checking the yjs specification, it should be clear, that only arrays are allowed. So i would change the issue to a feature request.
