### ISSUE TITLE
Cannot read properties of `null` when yArray.push([yDoc.getMap('x')])

### ISSUE THREAD

**Issue by Himself65** [yjs/yjs#458]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

```
➜  yjs-experimental git:(main) ✗ node subdoc.js
/Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:5853
    ;/** @type {Map<string, any>} */ (this._prelimContent).forEach((value, key) => {
                                                           ^

TypeError: Cannot read properties of null (reading 'forEach')
    at YMap._integrate (/Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:5853:60)
    at ContentType.integrate (/Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:9383:15)
    at Item.integrate (/Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:9962:20)
    at /Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:2354:12
    at Array.forEach (<anonymous>)
    at ListIterator.insertContents (/Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:2352:13)
    at ListIterator.insertArrayValue (/Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:2431:10)
    at /Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:5601:20
    at useSearchMarker (/Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:4888:12)
    at /Users/himself65/WebstormProjects/yjs-experimental/node_modules/.pnpm/yjs@13.6.0-2/node_modules/yjs/dist/yjs.cjs:5600:11

Node.js v18.7.0
```

**To Reproduce**

```js
const assert = require('node:assert')
const Y = require('yjs')
const rootDoc = new Y.Doc()
const subDoc = new Y.Doc()

const sheet1 = rootDoc.getMap('sheet')
const emptySheet = new Y.Map()

const list = subDoc.getArray('list')
// change `throws` to `doesNotThrow`
assert.throws(() => {
  list.push([sheet1])
})
assert.doesNotThrow(() => {
  list.push([emptySheet])
})
assert.doesNotThrow(() => {
  const ref = {
    sheet: sheet1
  }
  list.push([ref])
})
```

**Expected behavior**

`list.push([sheet1])` shouldn't throw error

**Environment Information**
nodejs = 18.7.0
yjs =13.5.41

**Additional context**

**Comment by Himself65** [comment]
I was meant to implement a list that hold the yMap list something like subdocument, but it throw error

**Comment by dmonad** [comment]
A shared type can only exist once in a document. It can't exist both as the root-level type and as a child element of another shared type. The documentation explains how to create nested structures: https://docs.yjs.dev/getting-started/working-with-shared-types

Similar issues have been reported several times. I'll leave this ticket open because I want to add a proper exception type that links to the documentation.
