### ISSUE TITLE
Not compatible with y-websocket and NextJS production build

### ISSUE THREAD

**Issue by 6peterlu** [yjs/yjs#489]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
When using y-websocket and deploying a NextJS production build, I encounter the following error:
```
ReferenceError: Cannot access 'C' before initialization
    at Object.QP (Skip.js:60:1)
    at 6292 (YArray.js:45:29)
    at l (bootstrap:21:1)
    at 8697 (ContentString.js:112:8)
    at l (bootstrap:21:1)
    at 8535 (Skip.js:60:1)
    at l (bootstrap:21:1)
    at 5021 (DeleteSet.js:325:1)
    at l (bootstrap:21:1)
    at 3838 (StructStore.js:261:5)
```
This error does not occur during the local development build. This occurs even if I set the components that are loading y-websocket to `ssr: false`.

**To Reproduce**
1. Create a NextJS project.
2. Import y-websocket and load the `WebsocketProvider` in some page.
3. `next build` to make a production build of the app.
4. `next start` to run the production build locally.

**Expected behavior**
Expected no error.

**Screenshots**
<img width="647" alt="image" src="https://user-images.githubusercontent.com/8334251/210093817-21fb9a18-df69-4534-b358-31519fea1e3b.png">

**Environment Information**
 - Browser / Node.js [e.g. Chrome, Firefox, Node.js]
 - Chromium browser version `108.0.5359.125`, NextJS version `13.1.1`
 - Yjs `13.5.41`, y-websocket `1.4.5`

**Additional context**
When loading the page I see this view:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/8334251/210094037-8b3901b7-adf2-43d5-b987-32c24055824f.png">

**Comment by 6peterlu** [comment]
Actually, this comment fixed my issue! 
https://github.com/yjs/yjs/issues/410#issuecomment-1127478919
